from backend.models.animal import AnimalIcon, AnimalType, Species, SpecieTrait

SPECIE_TRAITS_MAP: dict[Species, SpecieTrait] = {
    Species.ELEPHANT: SpecieTrait(
        name="Elephant",
        age_range=(5, 60),
        length_range=(250, 700),
        weight_range=(2000, 6000),
        animal_type=AnimalType.MAMMAL,
        icon=AnimalIcon.ELEPHANT,
    ),
    Species.GAUR: SpecieTrait(
        name="Gaur",
        age_range=(3, 20),
        length_range=(250, 350),
        weight_range=(600, 1000),
        animal_type=AnimalType.MAMMAL,
        icon=AnimalIcon.GAUR,
    ),
    Species.LEOPARD: SpecieTrait(
        name="Leopard",
        age_range=(2, 17),
        length_range=(90, 150),
        weight_range=(30, 90),
        animal_type=AnimalType.MAMMAL,
        icon=AnimalIcon.LEOPARD,
    ),
    Species.SUN_BEAR: SpecieTrait(
        name="Sun Bear",
        age_range=(2, 25),
        length_range=(100, 150),
        weight_range=(30, 80),
        animal_type=AnimalType.MAMMAL,
        icon=AnimalIcon.SUN_BEAR,
    ),
    Species.DHOLE: SpecieTrait(
        name="Dhole",
        age_range=(1, 10),
        length_range=(80, 120),
        weight_range=(10, 25),
        animal_type=AnimalType.MAMMAL,
        icon=AnimalIcon.DHOLE,
    ),
    Species.PORCUPINE: SpecieTrait(
        name="Porcupine",
        age_range=(1, 15),
        length_range=(40, 90),
        weight_range=(5, 15),
        animal_type=AnimalType.MAMMAL,
        icon=AnimalIcon.PORCUPINE,
    ),
    Species.PANGOLIN: SpecieTrait(
        name="Pangolin",
        age_range=(1, 10),
        length_range=(40, 100),
        weight_range=(4, 12),
        animal_type=AnimalType.MAMMAL,
        icon=AnimalIcon.PANGOLIN,
    ),
    Species.MONITOR_LIZARD: SpecieTrait(
        name="Monitor Lizard",
        age_range=(1, 20),
        length_range=(70, 200),
        weight_range=(5, 30),
        animal_type=AnimalType.REPTILE,
        icon=AnimalIcon.MONITOR_LIZARD,
    ),
    Species.HORNBILL: SpecieTrait(
        name="Hornbill",
        age_range=(2, 40),
        length_range=(70, 120),
        weight_range=(2, 4),
        animal_type=AnimalType.BIRD,
        icon=AnimalIcon.HORNBILL,
    ),
    Species.PEAFOWL: SpecieTrait(
        name="Peafowl",
        age_range=(1, 15),
        length_range=(90, 200),
        weight_range=(3, 6),
        animal_type=AnimalType.BIRD,
        icon=AnimalIcon.PEAFOWL,
    ),
    Species.VULTURE: SpecieTrait(
        name="Vulture",
        age_range=(2, 30),
        length_range=(80, 130),
        weight_range=(5, 12),
        animal_type=AnimalType.BIRD,
        icon=AnimalIcon.VULTURE,
    ),
    Species.KINGFISHER: SpecieTrait(
        name="Kingfisher",
        age_range=(1, 10),
        length_range=(15, 25),
        weight_range=(0.05, 0.1),
        animal_type=AnimalType.BIRD,
        icon=AnimalIcon.KINGFISHER,
    ),
    Species.PYTHON: SpecieTrait(
        name="Python",
        age_range=(1, 25),
        length_range=(200, 600),
        weight_range=(20, 90),
        animal_type=AnimalType.REPTILE,
        icon=AnimalIcon.PYTHON,
    ),
    Species.LANGUR: SpecieTrait(
        name="Langur",
        age_range=(1, 20),
        length_range=(40, 75),
        weight_range=(5, 15),
        animal_type=AnimalType.MAMMAL,
        icon=AnimalIcon.LANGUR,
    ),
    Species.CIVET: SpecieTrait(
        name="Civet",
        age_range=(1, 15),
        length_range=(50, 90),
        weight_range=(3, 7),
        animal_type=AnimalType.MAMMAL,
        icon=AnimalIcon.CIVET,
    ),
    Species.WILD_BOAR: SpecieTrait(
        name="Wild Boar",
        age_range=(1, 12),
        length_range=(100, 180),
        weight_range=(50, 150),
        animal_type=AnimalType.MAMMAL,
        icon=AnimalIcon.WILD_BOAR,
    ),
    Species.GECKO: SpecieTrait(
        name="Gecko",
        age_range=(1, 8),
        length_range=(10, 30),
        weight_range=(0.02, 0.2),
        animal_type=AnimalType.REPTILE,
        icon=AnimalIcon.GECKO,
    ),
    Species.EAGLE: SpecieTrait(
        name="Eagle",
        age_range=(3, 25),
        length_range=(60, 100),
        weight_range=(3, 7),
        animal_type=AnimalType.BIRD,
        icon=AnimalIcon.EAGLE,
    ),
    Species.OWL: SpecieTrait(
        name="Owl",
        age_range=(2, 20),
        length_range=(30, 60),
        weight_range=(1, 4),
        animal_type=AnimalType.BIRD,
        icon=AnimalIcon.OWL,
    ),
    Species.TORTOISE: SpecieTrait(
        name="Tortoise",
        age_range=(5, 100),
        length_range=(20, 100),
        weight_range=(10, 200),
        animal_type=AnimalType.REPTILE,
        icon=AnimalIcon.TORTOISE,
    ),
}
